### ISSUE TITLE
How to get 6,000 reduced imagenet samples

### ISSUE THREAD

**Issue by zhanghang1989** [kakaobrain/fast-autoaugment#37] opened 2020-02-06 23:02 UTC
The provided code first subsample 6,000 images, but then filter out irrelevant classes. Therefore, the resulting dataset is much smaller:

https://github.com/kakaobrain/fast-autoaugment/blob/master/FastAutoAugment/data.py#L132-L163

**Comment by zhanghang1989** [comment] 2020-02-06 23:07
The 120 classes not unique. 
```
idx120 = list(set(idx120))
len(idx120)
Out[4]: 110
```

**Comment by ildoonet** [comment] 2020-02-07 01:41
1. Sorry for the mistake. We modified the code by mistake for another issue. 
First, we sample 500000 training data(approximately 500 samples for each 1k classes) and then we sample 120 classes. This will get us approximately 500 samples for each random 120 classes.

2. As you pointed out, we used 110 classes by mistake. This is not intended. The result in our paper was from this 110 classes. If you want to, please make a pull request which modify code to use exclusive 120 classes. It might lead to a slightly better result.

Thanks for reporting this!

**Comment by zhanghang1989** [comment] 2020-02-07 01:48
Thanks for the reply!  BTW, it is a great work.

1. I swap the sequence of the operations by first get the samples from 120 classes and then get the 6000 splits.
2. An easy way to get 120 unique classes can be:
```
idx120 = sorted(random.sample(list(range(1000)), k=120))
```

**Comment by ildoonet** [comment] 2020-02-07 01:54
@zhanghang1989 Thanks for the tip. I updated the repo as you suggested. But for the better reproducibility, I hardcoded indice. (Also swapping the sequence of code would be better, but I didn't do this at this time)

 If you don't need any assistance on this matter, please close this issue.

**Closed as completed** 2020-02-07 01:57 UTC
